import {createReadStream, createWriteStream} from 'node:fs';
import {
  appendFile,
  glob,
  mkdir,
  readFile,
  rename,
  unlink,
  writeFile,
} from 'node:fs/promises';
import {dirname} from 'node:path';
import {Readable, Transform} from 'node:stream';
import {pipeline} from 'node:stream/promises';

import {globSync} from 'glob';
import {compiler as ClosureCompiler} from 'google-closure-compiler';
import {getNativeImagePath} from 'google-closure-compiler/lib/utils.js';
import * as path from 'path';
import yargs from 'yargs';
import {hideBin} from 'yargs/helpers';

import {getPackageJson} from './gulpfiles/helper_tasks.mjs';

import {posixPath} from './helpers.js';

const argv = yargs(hideBin(process.argv)).parse();

// Paths are all relative to the repository root.  Do not include
// trailing slash.
//
// TODO(#5007): If you modify these values, you must also modify the
// corresponding values in the following files:
//
// - tests/scripts/check_metadata.sh
// - tests/scripts/update_metadata.sh

// Directory to write compiled output to.
export const BUILD_DIR = 'build';

// Directory to write typings output to.
export const TYPINGS_BUILD_DIR = path.join(BUILD_DIR, 'declarations');

// Directory to write langfile output to.
export const LANG_BUILD_DIR = path.join(BUILD_DIR, 'msg');

// Directory where typescript compiler output can be found.
// Matches the value in tsconfig.json: outDir
export const TSC_OUTPUT_DIR = path.join(BUILD_DIR, 'src');

// Directory for files generated by compiling test code.
export const TEST_TSC_OUTPUT_DIR = path.join(BUILD_DIR, 'tests');

// Directory in which to assemble (and from which to publish) the
// blockly npm package.
export const RELEASE_DIR = 'dist';

/**
 * Path to the python runtime.
 * This will normalize the command across platforms (e.g. python3 on Linux and
 * Mac, python on Windows).
 */
const PYTHON = process.platform === 'win32' ? 'python' : 'python3';

/**
 * Posix version of TSC_OUTPUT_DIR
 */
const TSC_OUTPUT_DIR_POSIX = posixPath(TSC_OUTPUT_DIR);

/**
 * Suffix to add to compiled output files.
 */
const COMPILED_SUFFIX = '_compressed';

/**
 * Name of an object to be used as a shared "global" namespace by
 * chunks generated by the Closure Compiler with the
 * --rename_prefix_namespace option (see
 * https://github.com/google/closure-compiler/wiki/Chunk-output-for-dynamic-loading#using-global_namespace-as-the-chunk-output-type
 * for more information.)  The wrapper for the first chunk will create
 * an object with this name and save it; wrappers for other chunks
 * will ensure that the same object is available with this same name.
 * The --rename_prefix_namespace option will then cause the compiled
 * chunks to create properties on this object instead of creating
 * "global" (really chunk-local) variables.  This allows later chunks
 * to depend upon modules from earlier chunks.
 *
 * It can be any value that doesn't clash with a global variable or
 * wrapper argument, but as it will appear many times in the compiled
 * output it is preferable that it be short.
 */
const NAMESPACE_VARIABLE = '$';

/**
 * Property that will be used to store the value of the namespace
 * object on each chunk's exported object.  This is so that dependent
 * chunks can retrieve the namespace object and thereby access modules
 * defined in the parent chunk (or it's parent, etc.).  This should be
 * chosen so as to not collide with any exported name.
 */
const NAMESPACE_PROPERTY = '__namespace__';

/**
 * Directory (relative to TSC_OUTPUT_DIR) where generated chunk
 * exporters are written.
 *
 * See buildChunkExporters for additional information.
 */
const CHUNK_EXPORTERS_DIR = 'chunk_exporters';

/**
 * Prefix for properties that will be used to store each chunk's
 * export object on the namespace object.
 *
 * See buildChunkExporters for additional information.
 */
const CHUNK_EXPORTS_PREFIX = '__chunk_';

/**
 * A list of chunks.  Order matters: later chunks can depend on
 * earlier ones, but not vice-versa.  All chunks are assumed to depend
 * on the first chunk.  Properties are as follows:
 *
 * - .name: the name of the chunk.  Used to label it when describing
 *   it to Closure Compiler and forms the prefix of filename the chunk
 *   will be written to.  Should be a valid identifier.
 * - .files: A glob or array of globs, relative to TSC_OUTPUT_DIR,
 *   matching the files to include in the chunk.
 * - .entry: the source .js file which is the entrypoint for the
 *   chunk, relative to TSC_OUTPUT_DIR.
 * - .scriptExport: When the chunk is loaded as a script (e.g., via a
 *   <SCRIPT> tag), the chunk's exports object will be made available
 *   at the specified location (which must be a variable name or the
 *   name of a property on an already-existing object) in the global
 *   namespace.
 * - .scriptNamedExports: A map of {location: namedExport} pairs; when
 *   loaded as a script, the specified named exports will be saved at
 *   the specified locations (which again must be global variables or
 *   properties on already-existing objects).  Optional.
 * - .parent: the parent chunk of the given chunk; null for the root
 *   chunk.
 *
 * Output files will be named <chunk.name><COMPILED_SUFFIX>.js.
 */
const chunks = [
  {
    name: 'blockly',
    files: 'core/**/*.js',
    entry: 'core/blockly.js',
    scriptExport: 'Blockly',
  },
  {
    name: 'blocks',
    files: 'blocks/**/*.js',
    entry: 'blocks/blocks.js',
    scriptExport: 'Blockly.libraryBlocks',
  },
  {
    name: 'javascript',
    files: ['generators/javascript.js', 'generators/javascript/**/*.js'],
    entry: 'generators/javascript.js',
    scriptExport: 'javascript',
    scriptNamedExports: {'Blockly.JavaScript': 'javascriptGenerator'},
  },
  {
    name: 'python',
    files: ['generators/python.js', 'generators/python/**/*.js'],
    entry: 'generators/python.js',
    scriptExport: 'python',
    scriptNamedExports: {'Blockly.Python': 'pythonGenerator'},
  },
  {
    name: 'php',
    files: ['generators/php.js', 'generators/php/**/*.js'],
    entry: 'generators/php.js',
    scriptExport: 'php',
    scriptNamedExports: {'Blockly.PHP': 'phpGenerator'},
  },
  {
    name: 'lua',
    files: ['generators/lua.js', 'generators/lua/**/*.js'],
    entry: 'generators/lua.js',
    scriptExport: 'lua',
    scriptNamedExports: {'Blockly.Lua': 'luaGenerator'},
  },
  {
    name: 'dart',
    files: ['generators/dart.js', 'generators/dart/**/*.js'],
    entry: 'generators/dart.js',
    scriptExport: 'dart',
    scriptNamedExports: {'Blockly.Dart': 'dartGenerator'},
  },
];

chunks[0].parent = null;
for (let i = 1; i < chunks.length; i++) {
  chunks[i].parent = chunks[0];
}

/**
 * Return the name of the module object for the entrypoint of the
 * given chunk, as munged by Closure Compiler.
 *
 * Note that if either --assume_function_wrapper or
 * --compilation_level ADVANCED_OPTIMIZATIONS is used then the name
 * will be further munged in a later compliation step to replace it
 * with an arbitrary, very short name.
 *
 * Nevertheless, this function can still be used to compute the
 * location of @defined variables, because --define directives are
 * processed before the final renaming occurs.
 */
function modulePath(chunk) {
  const entryPath = path.posix.join(TSC_OUTPUT_DIR_POSIX, chunk.entry);
  return 'module$' + entryPath.replace(/\.js$/, '').replaceAll('/', '$');
}

const licenseRegex = `\\/\\*\\*
 \\* @license
 \\* (Copyright \\d+ (Google LLC|Massachusetts Institute of Technology|Raspberry Pi Foundation))
( \\* All rights reserved.
)? \\* SPDX-License-Identifier: Apache-2.0
 \\*\\/`;

/**
 * Helper method for stripping the Google's and MIT's Apache Licenses.
 *
 * @param {!Array<string>} filePaths Files to rewrite.
 */
async function stripApacheLicenses(filePaths) {
  await Promise.all(
    filePaths.map(async (filePath) => {
      const source = await readFile(filePath, 'utf8');
      // Strip out Google's and MIT's Apache licences.
      // Closure Compiler preserves dozens of Apache licences in the Blockly code.
      // Remove these if they belong to Google or MIT.
      // MIT's permission to do this is logged in Blockly issue #2412.
      const stripped = source.replace(
        new RegExp(licenseRegex, 'g'),
        '\n\n\n\n',
      );
      // Replace with the same number of lines so that source-maps are
      // not affected.
      if (stripped !== source) await writeFile(filePath, stripped);
    }),
  );
}

/**
 * Closure Compiler diagnostic groups we want to be ignored.  These
 * suppressions are always effected by default.
 *
 * Make sure that anything added here is commented out of JSCOMP_ERROR
 * above, as that takes precedence.)
 */
const JSCOMP_OFF = [
  /* The removal of Closure type system types from our JSDoc
   * annotations means that the Closure Compiler now generates certain
   * diagnostics because it no longer has enough information to be
   * sure that the input code is correct.  The following diagnostic
   * groups are turned off to suppress such errors.
   *
   * When adding additional items to this list it may be helpful to
   * search the compiler source code
   * (https://github.com/google/closure-compiler/) for the JSC_*
   * diagnostic name (omitting the JSC_ prefix) to find the corresponding
   * DiagnosticGroup.
   */
  'checkTypes',
  'nonStandardJsDocs', // Due to @internal
  'unusedLocalVariables', // Due to code generated for merged namespaces.

  /* In order to transition to ES modules, modules will need to import
   * one another by relative paths. This means that the previous
   * practice of moving all source files into the same directory for
   * compilation would break imports.
   *
   * Not flattening files in this way breaks our usage
   * of @package however: files were flattened so that all Blockly
   * source files are in the same directory and can use @package to
   * mark methods that are only allowed for use by Blockly, while
   * still allowing access between e.g. core/events/* and
   * core/utils/*. We were downgrading access control violations
   * (including @private) to warnings, but this ends up being so
   * spammy that it makes the compiler output nearly useless.
   *
   * Once ES module migration is complete, they will be re-enabled and
   * an alternative to @package will be established.
   */
  'visibility',
];

async function globsToArray(globPatterns) {
  const filePaths = [];
  for await (const file of glob(globPatterns)) {
    filePaths.push(file);
  }
  return filePaths;
}
/**
 * Helper function that takes in a list of src patterns, a destination file, and
 * a list of transforms to apply and returns a pipeline that writes to the
 * destination file path.
 *
 * @param {Array<string>} globPatterns The patterns to match for the input files
 * @param {string} destFile The path of the destination file
 * @param  {...Transform} transforms The transformations to pipe the data
 * through
 * @returns
 */
async function concatPipeline(globPatterns, destFile, ...transforms) {
  // Ensure the destination directory exists
  await mkdir(dirname(destFile), {recursive: true});

  // Get an array of all matching files
  const filePaths = await globsToArray(globPatterns);

  // Create a generator that yields the content of each file one by one
  async function* mergeFiles() {
    for (const file of filePaths) {
      const fileStream = createReadStream(file);
      for await (const chunk of fileStream) {
        yield chunk;
      }
    }
  }

  // Wrap the generator into a readable stream
  const combinedReadable = Readable.from(mergeFiles());

  // Pipe everything through your transforms to the final file
  return pipeline(combinedReadable, ...transforms, createWriteStream(destFile));
}

/**
 * Return the path to the generated chunk exporter for the given
 * chunk, relative to TSC_OUTPUT_DIR.
 *
 * See buildChunkExporters for additional information.
 *
 * @param {{name: string}} chunk
 * @return {string}
 */
function chunkExporterPath(chunk) {
  return path.posix.join(CHUNK_EXPORTERS_DIR, `${chunk.name}_exporter.js`);
}

/**
 * This task generates the chunk exporters, one per chunk, which are
 * source files included in the input to Closure Compiler to help the
 * chunk wrappers locate the chunk's exports (module) object.
 *
 * Normally, when using --compilation_level SIMPLE_OPTIMIZATIONS and
 * --chunk_output_type GLOBAL_NAMESPACE (the defaults), Closure
 * Compiler will give each chunk's top-level exports (module) object a
 * name of the form
 *
 *    module$build$src$...$filename
 *
 * which can be computed by modulePath(chunk), thereby making it easy
 * to locate the object that should be returned by the chunk wrapper's
 * factory function.
 *
 * Unfortunately, if using using --assume_function_wrapper option (or
 * --compilation_level ADVANCED_OPTIMIZATIONS), this variable is
 * renamed in a later stage of the compiler to instead have an
 * arbitrarily-chosen name of minimal length.
 *
 * To work around this, we create an extra source module for each
 * chunk that imports the chunk's entrypoint and saves the resulting
 * exports (module) object to a well-known location: a property on the
 * shared namespace object.
 *
 * In order to prevent the name of that property from itself being
 * renamed, well-known location, it is written using a computed member
 * expression with a string literal property name (i.e., a['b'] rather
 * than a.b).  E.g., the the generated chunck exporter source file
 * might contain
 *
 *     import * as exports from '../core/blockly.js';
 *     $['__chunk_blockly'] = exports;
 *
 * which would get compiled to something like:
 *
 *     $.__chunk_blockly=R;
 *
 * The chunk wrapper's factory function can then retrieve
 * and return $.__chunk_blockly.
 *
 * N.B.: Although Closure Compiler will not rename the literal
 * property name, it will convet the computed member expression into a
 * non-computed one (as shown in the example above) if it is a valid
 * unquoted property name.  In order to ensure that the compiled,
 * wrapped chunk is itself valid input for Closure Compiler, it is
 * necessary that the chunk wrapper use the same form to access it.
 * Specifically, for this example the chunk wrapper factory function
 * should
 *
 *     return $.__chunk_blockly;
 *
 * rather than
 *
 *     return $['__chunk_blockly'];
 */
async function buildChunkExporters() {
  const outDir = path.join(TSC_OUTPUT_DIR, CHUNK_EXPORTERS_DIR);
  await mkdir(outDir, {recursive: true});

  await Promise.all(
    chunks.map(async (chunk) => {
      const filename = chunkExporterPath(chunk);
      const importPath = posixPath(
        path.posix.relative(path.posix.dirname(filename), chunk.entry),
      );
      await writeFile(
        path.join(TSC_OUTPUT_DIR, filename),
        // Suppress undefined-variable diagnostics, since Closure
        // Compiler can't see the declaration of NAMESPACE_VARIABLE
        // while compiling the chunk exporters.
        `/** @fileoverview @suppress {undefinedVars} */

import * as exports from '${importPath}';
${NAMESPACE_VARIABLE}['${CHUNK_EXPORTS_PREFIX}${chunk.name}'] = exports;
`,
      );
    }),
  );
}

/**
 * A helper method to return an Closure Compiler chunk wrapper that
 * wraps the compiler output for the given chunk in a Universal Module
 * Definition.
 */
function chunkWrapper(chunk) {
  // Each chunk can have only a single dependency, which is its parent
  // chunk.  It is used only to retrieve the namespace object, which
  // is saved on to the exports object for the chunk so that any child
  // chunk(s) can obtain it.

  // JavaScript expressions for the amd, cjs and browser dependencies.
  let amdDepsExpr = '';
  let cjsDepsExpr = '';
  let scriptDepsExpr = '';
  // Arguments for the factory function.
  let factoryArgs = '';
  // Expression to get or create the namespace object.
  let namespaceExpr = `{}`;

  if (chunk.parent) {
    const parentFilename = JSON.stringify(
      `./${chunk.parent.name}${COMPILED_SUFFIX}.js`,
    );
    amdDepsExpr = parentFilename;
    cjsDepsExpr = `require(${parentFilename})`;
    scriptDepsExpr = `root.${chunk.parent.scriptExport}`;
    factoryArgs = '__parent__';
    namespaceExpr = `${factoryArgs}.${NAMESPACE_PROPERTY}`;
  }

  // Code to save the chunk's exports object at chunk.scriptExport and
  // additionally save individual named exports as directed by
  // chunk.scriptNamedExports.
  const scriptExportStatements = [
    `root.${chunk.scriptExport} = factory(${scriptDepsExpr});`,
  ];
  for (var location in chunk.scriptNamedExports) {
    const namedExport = chunk.scriptNamedExports[location];
    scriptExportStatements.push(
      `root.${location} = root.${chunk.scriptExport}.${namedExport};`,
    );
  }

  // Expression evaluating to the location on the namespace object at
  // which the chunk exporter will have saved the chunk's exports
  // object.  (See buildChunkExporters.)
  const exportsObject = `${NAMESPACE_VARIABLE}.${CHUNK_EXPORTS_PREFIX}${chunk.name}`;

  // Generate wrapper.
  return `// Do not edit this file; automatically generated.

/* eslint-disable */
;(function(root, factory) {
  if (typeof define === 'function' && define.amd) { // AMD
    define([${amdDepsExpr}], factory);
  } else if (typeof exports === 'object') { // Node.js
    module.exports = factory(${cjsDepsExpr});
  } else { // Script
    ${scriptExportStatements.join('\n    ')}
  }
}(this, function(${factoryArgs}) {
var ${NAMESPACE_VARIABLE}=${namespaceExpr};
%output%
${exportsObject}.${NAMESPACE_PROPERTY}=${NAMESPACE_VARIABLE};
return ${exportsObject};
}));
`;
}

/**
 * Compute the chunking options to pass to Closure Compiler.  Output
 * is in the form:
 *
 * {
 *   "chunk": [
 *     "blockly:286",
 *     "blocks:10:blockly",
 *     "javascript:11:blockly",
 *     // ... one per chunk
 *   ],
 *   "js": [
 *     "build/src/core/any_aliases.js",
 *     "build/src/core/block.js",
 *     "build/src/core/block_animations.js",
 *     // ... many more files, in order by chunk
 *   ],
 *   "chunk_wrapper": [
 *     "blockly:// Do not edit this file...",
 *     "blocks:// Do not edit this file...",
 *     // ... one per chunk
 *   ]
 * }
 *
 * This is designed to be passed directly as-is as the options object
 * to the Closure Compiler node API, and be compatible with that
 * emitted by closure-calculate-chunks.
 *
 * N.B.: items in the .chunk array are of the form:
 *
 *     "<chunk name>:<file count>:<parent chunk name>"
 *
 * See https://github.com/google/closure-compiler/wiki/Flags-and-Options#code-splitting
 * for more information.
 *
 * @return {{chunk: !Array<string>,
 *           js: !Array<string>,
 *           chunk_wrapper: !Array<string>}}
 *     The chunking options, in the format described above.
 */
function getChunkOptions() {
  const chunkOptions = [];
  const allFiles = [];

  for (const chunk of chunks) {
    const globs = typeof chunk.files === 'string' ? [chunk.files] : chunk.files;
    const files = globs
      .flatMap((glob) => globSync(glob, {cwd: TSC_OUTPUT_DIR_POSIX}))
      .map((file) => path.posix.join(TSC_OUTPUT_DIR_POSIX, file));
    files.push(path.posix.join(TSC_OUTPUT_DIR_POSIX, chunkExporterPath(chunk)));
    chunkOptions.push(
      `${chunk.name}:${files.length}` +
        (chunk.parent ? `:${chunk.parent.name}` : ''),
    );
    allFiles.push(...files);
  }

  const chunkWrappers = chunks.map(
    (chunk) => `${chunk.name}:${chunkWrapper(chunk)}`,
  );

  return {chunk: chunkOptions, js: allFiles, chunk_wrapper: chunkWrappers};
}

/**
 * Helper method for calling the Closure Compiler, establishing
 * default options (that can be overridden by the caller).
 *
 * The compiler reads its inputs from and writes its outputs to disk,
 * so the caller is expected to supply --js and either --js_output_file
 * or --chunk_output_path_prefix.
 *
 * @param {{[flag: string]: string|boolean|!Array<string>}} options
 *     Caller-supplied options that will override the defaultOptions.
 * @return {!Promise<string>} Resolves with the compiler's stdout once
 *     it exits successfully; rejects if it exits non-zero.
 */
function compile(options) {
  const defaultOptions = {
    compilation_level: 'SIMPLE_OPTIMIZATIONS',
    warning_level: argv.verbose ? 'VERBOSE' : 'DEFAULT',
    language_in: 'ECMASCRIPT_2020',
    language_out: 'ECMASCRIPT_2015',
    jscomp_off: [...JSCOMP_OFF],
    rewrite_polyfills: true,
    hide_warnings_for: ['node_modules'],
    define: ['COMPILED=true'],
  };
  if (argv.debug || argv.strict) {
    defaultOptions.jscomp_error = [...JSCOMP_ERROR];
    defaultOptions.jscomp_warning = [...JSCOMP_WARNING];
    if (argv.strict) {
      defaultOptions.jscomp_error.push('strictCheckTypes');
    }
  }
  
  const compilerInstance = new ClosureCompiler({...defaultOptions, ...options});

  // google-closure-compiler's node API always shells out to `java`
  // unless JAR_PATH is cleared; only its gulp and grunt plugins know
  // about the platform-native binaries.  Do what those plugins do, so
  // that a JRE isn't needed on platforms we ship a binary for.  See
  // getFirstSupportedPlatform() in google-closure-compiler/lib/utils.js.
  const nativeImagePath = getNativeImagePath();
  if (nativeImagePath) {
    compilerInstance.JAR_PATH = null;
    compilerInstance.javaPath = nativeImagePath;
  } else if (!process.env.JAVA_HOME) {
    throw new Error(
      'No native Closure Compiler binary for this platform and no JRE ' +
        'found; set JAVA_HOME or install google-closure-compiler-<platform>.',
    );
  }

  return new Promise((resolve, reject) => {
    compilerInstance.run((exitCode, stdout, stderr) => {
      // Diagnostics go to stderr even when compilation succeeds.
      if (stderr) process.stderr.write(stderr);
      if (exitCode === 0) {
        resolve(stdout);
      } else {
        reject(new Error(`Closure Compiler exited with code ${exitCode}.`));
      }
    });
  });
}

/**
 * This task compiles the core library, blocks and generators, creating
 * blockly_compressed.js, blocks_compressed.js, etc.
 */
async function buildCompiled() {
  // Get chunking.
  const chunkOptions = getChunkOptions();
  // Closure Compiler options.
  const packageJson = getPackageJson(); // For version number.
  const options = {
    // The documentation for @define claims you can't use it on a
    // non-global, but the Closure Compiler turns everything in to a
    // global - you just have to know what the new name is!  With
    // declareLegacyNamespace this was very straightforward.  Without
    // it, we have to rely on implmentation details.  (Note that
    // although --assume_function_wrapper will result in the global
    // being renamed to something short, that won't have happened
    // by the time --define is processed.)  See
    // https://github.com/google/closure-compiler/issues/1601#issuecomment-483452226
    define: `VERSION$$${modulePath(chunks[0])}='${packageJson.version}'`,
    js: chunkOptions.js,
    chunk: chunkOptions.chunk,
    chunk_wrapper: chunkOptions.chunk_wrapper,
    // Closure writes one file per chunk, named after the chunk, so
    // this produces e.g. dist/blockly.js; the COMPILED_SUFFIX is added
    // below.
    chunk_output_path_prefix: `${RELEASE_DIR}/`,
    create_source_map: '%outname%.map',
    rename_prefix_namespace: NAMESPACE_VARIABLE,
    assume_function_wrapper: true,
  };

  await stripApacheLicenses(chunkOptions.js);
  // Ensure the destination directory exists
  await mkdir(RELEASE_DIR, {recursive: true});
  await compile(options);

  // Closure names each chunk's output after the chunk itself and has
  // no equivalent of gulp-rename, so add COMPILED_SUFFIX here, fixing
  // up the source map's reference to its own output file as we go.  It
  // also doesn't emit the sourceMappingURL comment that gulp-sourcemaps
  // used to append.
  for (const chunk of chunks) {
    const compiledPath = path.join(RELEASE_DIR, `${chunk.name}.js`);
    const outputName = `${chunk.name}${COMPILED_SUFFIX}.js`;
    const outputPath = path.join(RELEASE_DIR, outputName);

    const sourceMap = JSON.parse(await readFile(`${compiledPath}.map`, 'utf8'));
    sourceMap.file = outputName;
    // Closure can only embed source content that its inputs' own source
    // maps carry, and tsc's don't carry any, so read the originals off
    // disk.  Paths in .sources are relative to the package root.
    sourceMap.sourcesContent = await Promise.all(
      sourceMap.sources.map((source) =>
        readFile(source, 'utf8').catch(() => null),
      ),
    );
    await writeFile(`${outputPath}.map`, JSON.stringify(sourceMap));
    await unlink(`${compiledPath}.map`);

    await rename(compiledPath, outputPath);
    await appendFile(outputPath, `\n//# sourceMappingURL=${outputName}.map\n`);
  }
}


/**
 * This task uses Closure Compiler's ADVANCED_OPTIMIZATIONS mode to
 * compile together Blockly core, blocks and generators with a simple
 * test app; the purpose is to verify that Blockly is compatible with
 * the ADVANCED_OPTIMIZATIONS mode.
 *
 * Prerequisite: tsc (handled by nx).
 */

async function compileAdvancedCompilationTest() {
  // If main_compressed.js exists (from a previous run) delete it so that
  // a later browser-based test won't check it should the compile fail.
  try {
    fs.unlinkSync('./tests/compile/main_compressed.js');
  } catch {
    // Probably it didn't exist.
  }
  const srcs = [
    TSC_OUTPUT_DIR + '/**/*.js',
    'tests/compile/main.js',
    'tests/compile/test_blocks.js',
  ];

  // Closure Compiler options.
  const options = {
    dependency_mode: 'PRUNE',
    compilation_level: 'ADVANCED_OPTIMIZATIONS',
    entry_point: './tests/compile/main.js',
    js_output_file: 'main_compressed.js',
  };

  try {
    await concatPipeline(
      srcs,
      './tests/compile/main_compressed.js',
      // sourcemaps?
      // compile
    );
    console.log('Scripts bundled successfully!');
  } catch (err) {
    console.error('Bundling failed:', err);
  }
}

/**
 * 
 * Prerequisite: tsc (handled by nx).
*/
async function minify() {
  await buildChunkExporters();
  await buildCompiled();
}

// compileAdvancedCompilationTest();
minify();
